### ISSUE TITLE
Add a way to ignore elements for size calculation, inverse of data-iframe-size

### ISSUE THREAD

**Issue by bertho-zero** [davidjbradshaw/iframe-resizer#1395]
It happens randomly that iframe-resizer resizes my page to several hundred thousand pixels because of leaflet which temporarily creates an element of this type:
```html
<div class="leaflet-proxy leaflet-zoom-animated" style="transform: translate3d(2.12497e+06px, 1.44227e+06px, 0px) scale(8192);" data-overflowed=""></div>
```
I can fix the problem by adding `data-iframe-size` on my `body` but I would rather do the opposite, just ignore this leaflet card in the calculation.

**Comment by bertho-zero** [comment]
Ah, I can't, on a parent would be ideal

**Comment by davidjbradshaw** [comment]
@bertho-zero  That turned out to be pretty simple to do. If you want to download the latest beta version and give it a try.

```sh
npm instal @iframe-resizer/child@beta
```

```js
 window.iFrameResizer = {
   ignoreSelector: '.leaflet-proxy.leaflet-zoom-animated',
 }
```

I would be grateful if you could let me know if it works for you.

**Comment by bertho-zero** [comment]
I have an error with the latest beta

![Image](https://github.com/user-attachments/assets/30f5f1be-4be9-4133-b5c8-552b6e67c7ff)

![Image](https://github.com/user-attachments/assets/a6aca7ba-8262-4758-84f0-860c74ed000a)

**Comment by davidjbradshaw** [comment]
OK I think I know what that is and should have another beta out by the end of the day. Thanks for flagging.

**Comment by bertho-zero** [comment]
This looks like a bug following the `auto-console-group` update

https://github.com/davidjbradshaw/iframe-resizer/blob/ebbf323cbb7e76dab5761e7b2a409ca144c44c36/packages/child/console.js#L10

**Comment by davidjbradshaw** [comment]
Yeah that is another new project of mine and I think I was running `npm link` when I published the last beta. I just have a couple of things and then I will publish the final version of `auto-console-group` and then another beta.

**Comment by bertho-zero** [comment]
Ok, I added a `.default` directly in the node_modules so I can test `ignoreSelector` while waiting on my side but I still have a giant page, here are some logs:

![Image](https://github.com/user-attachments/assets/1c04736f-9198-479c-9330-c90037c2c574)

![Image](https://github.com/user-attachments/assets/fbb6c6c5-5c5d-4265-bc8b-2b91a9cb61b8)

**Comment by davidjbradshaw** [comment]
Is it possible to send me a link, so I can take a look at what is happening?

**Comment by bertho-zero** [comment]
This one for example: https://mougins.fr/a_test/

**Comment by davidjbradshaw** [comment]
Just published beta 4, can you please let me know if it fixes the import of `auto-console-group` for you.

**Comment by bertho-zero** [comment]
I have the same error

**Comment by davidjbradshaw** [comment]
Can you send me a link to a running page with the error, as I cannot reproduce it here.

**Comment by bertho-zero** [comment]
I can't put this error into production, many customers would be impacted, maybe I can send you a tunnel privately?

The child is in a next app, the parent just has a small script built with webpack

**Comment by davidjbradshaw** [comment]
Ok I had another idea, I've just added the following to `beta.6`

```js
import acg from 'auto-console-group'

// Deal with UMD not converting default exports to named exports
const createGroupConsole = typeof acg === 'function' ? acg : acg.default
```

I've also updated the child types in this one.

Hopefully this fixes both issues.

**Comment by bertho-zero** [comment]
I see two problems with `auto-console-group`.

1. It won't work in a native Node environment with ESM because it's missing an `exports` field, Node doesn't look at the `module` field in package.json.
This problem can be seen here: https://publint.dev/auto-console-group
The [Vite documentation](https://vite.dev/guide/build#library-mode) recommends a package.json that looks like this:
```json
{
  "name": "my-lib",
  "type": "module",
  "files": ["dist"],
  "main": "./dist/my-lib.umd.cjs",
  "module": "./dist/my-lib.js",
  "exports": {
    ".": {
      "import": "./dist/my-lib.js",
      "require": "./dist/my-lib.umd.cjs"
    }
  }
}
```

2. It uses a default export alongside named exports (https://github.com/davidjbradshaw/auto-console-group/blob/0a7b261c63a461a87aa3d92c338cb394bac2f022/lib/index.ts#L11-L14), when it's converted to CJS you will have a `default` key next to the others, we see this in the index.umd.cjs output:

```js
/*!
*  @module      auto-console-group
*  @description Automagically group console messages
*  @author      David J. Bradshaw
*  @copyright  (c)2025 David J. Bradshaw. All rights reserved.
*  @license     MIT
*/
n.BOLD = m, n.FOREGROUND = S, n.HIGHLIGHT = R, n.ITALIC = g, n.NORMAL = r, n.default = F, Object.defineProperties(n, {
  __esModule: { value: !0 },
  [Symbol.toStringTag]: { value: 'Module' },
});
```
When the following line is built in CJS:

`import createGroupConsole from 'auto-console-group'`

we get an object with `default` and the other values ​​next to it:

![Image](https://github.com/user-attachments/assets/4f702fb2-6de2-4817-8719-db1ab3b54cff)

**Comment by davidjbradshaw** [comment]
I'm new to Vite and struggling a bit with it, so would welcome any suggestions you have on how to fix this.

**Comment by bertho-zero** [comment]
I've never used Vite, it was more to illustrate the lack of `exports` in the package.json which will quickly become a hindrance for people who use Node in 100% ESM.

-----

When I have the problem with esm/cjs, I do something like:

```js
import acg from 'auto-console-group'

const createGroupConsole = acg.default || acg
```

The more "official" solution would be to use something that relies on `__esModule`, like this:

```js
import acg from 'auto-console-group'

const createGroupConsole = acg.__esModule ? acg.default : acg

// or
function esModuleInterop(mod) {
  return mod && mod.__esModule ? mod.default : mod;
}

const createGroupConsole = esModuleInterop(acg)
```

**Comment by bertho-zero** [comment]
I no longer have the `auto-console-group` error, I can activate the logs and go into production with this version tomorrow morning

**Comment by davidjbradshaw** [comment]
Just released beta 7 with updated `acg` and

```js
export const esModuleInterop = (mod) =>
  // eslint-disable-next-line no-underscore-dangle
  mod?.__esModule ? mod.default : mod
```

**Comment by davidjbradshaw** [comment]
Thank you for your help with both of those, let me know when you have this online and I can take a look to see what is happening with the map. What steps do I have to do to cause the error?

**Comment by bertho-zero** [comment]
I've created a .patch that applies https://github.com/davidjbradshaw/auto-console-group/pull/5 to my project, otherwise I can't release.

To see the `beta.8` with logs online you can look at:
https://www.calvados.fr/agenda
https://mougins.fr/a_test

**Comment by davidjbradshaw** [comment]
@bertho-zero still seeing the `e.replaceAll()` error on your link. I'm wondering if you roll back the latest Babel if it fixes anything? I'm going to have to pick this up tomorrow, as right now I am crawling back into bed.

**Comment by bertho-zero** [comment]
@davidjbradshaw I no longer have the `e.replaceAll` error, but I still have this randomly giant iframe problem with `beta.12`. Maybe you should delete your cache.

**Comment by davidjbradshaw** [comment]
Can you give me some steps to repro the big iframe issue. I have never been able to see it.

**Comment by bertho-zero** [comment]
I open https://www.calvados.fr/agenda in private browsing, I reload the page several times with CTRL + SHIFT + R, or I click on an event, then several times on the arrow for the next or previous event

**Comment by davidjbradshaw** [comment]
Can you passed the entire log output here from when it happens?

**Comment by bertho-zero** [comment]
```
4560.699ac1f5cd896295.js:14 oa-embed-0 message @ 15:42:28.866
_app-5ee16669ef044518.js:321 Sending message to host page via postMessage
_app-5ee16669ef044518.js:321 oa-embed-0:0:0:message:{"type":"urlChange","url":"/fr/embed/agendas/11317568/events/coupures-de-samuel-valensi-et-paul-eloi-forget-cie-la-poursuite-du-bleu"}
widgets.js:1 parent(oa-embed-0) message @ 15:42:28.870
widgets.js:1 Received: [iFrameSizer]oa-embed-0:0:0:message:{"type":"urlChange","url":"/fr/embed/agendas/11317568/events/coupures-de-samuel-valensi-et-paul-eloi-forget-cie-la-poursuite-du-bleu"}
widgets.js:1 onMessage passed: {iframe: oa-embed-0, message: {"type":"urlChange","url":"/fr/embed/agendas/11317568/events/coupures-de-samuel-valensi-et-paul-eloi-forget-cie-la-poursuite-du-bleu"}}
4560.699ac1f5cd896295.js:14 oa-embed-0 mutationObserver @ 15:42:28.908
_app-5ee16669ef044518.js:321 Mutations observed: 17
_app-5ee16669ef044518.js:321 Mutations observed: 1
_app-5ee16669ef044518.js:321 ignoreSelector: .leaflet-proxy.leaflet-zoom-animated
_app-5ee16669ef044518.js:321 Tagged elements found: false
_app-5ee16669ef044518.js:321 Attached overflowObservers
_app-5ee16669ef044518.js:321 Attached resizeObserver: A.chakra-link chakra-button oa-hq2kqx
_app-5ee16669ef044518.js:321 Attached resizeObserver: DIV.chakra-aspect-ratio oa-gb6vke
_app-5ee16669ef044518.js:321 Attached resizeObserver: DIV
2_app-5ee16669ef044518.js:321 Attached resizeObserver: BUTTON.chakra-button oa-arpbox
4560.699ac1f5cd896295.js:14 oa-embed-0 resizeObserver @ 15:42:28.909
_app-5ee16669ef044518.js:321 Resize event: Element resized <BODY.chakra-ui-light>
_app-5ee16669ef044518.js:321 <html> size equals page size: HTML: 1978.625px Page: 1979px
_app-5ee16669ef044518.js:321 Content height: 1978.625px
_app-5ee16669ef044518.js:321 Size calculated in 0.1ms
_app-5ee16669ef044518.js:321 Sending message to host page via postMessage
_app-5ee16669ef044518.js:321 oa-embed-0:1978.625:1140:resizeObserver
widgets.js:1 parent(oa-embed-0) resizeObserver @ 15:42:28.911
widgets.js:1 Received: [iFrameSizer]oa-embed-0:1978.625:1140:resizeObserver
widgets.js:1 Set height: 1978.625px
4560.699ac1f5cd896295.js:14 oa-embed-0 overflowObserver @ 15:42:28.919
_app-5ee16669ef044518.js:321 Observed Elements: 2
_app-5ee16669ef044518.js:321 Resize event: Overflow updated
_app-5ee16669ef044518.js:321 Found element overflowing <html> 
_app-5ee16669ef044518.js:321 Bottom position calculated from: <html lang=​"fr" style=​"color-scheme:​ light;​ height:​ auto !important;​" data-theme=​"light">​…​</html>​
_app-5ee16669ef044518.js:321 Content height: 1486.3125px
_app-5ee16669ef044518.js:321 Size calculated in 0.2ms
_app-5ee16669ef044518.js:321 Sending message to host page via postMessage
_app-5ee16669ef044518.js:321 oa-embed-0:1486.3125:1140:overflowObserver
4560.699ac1f5cd896295.js:14 oa-embed-0 mutationObserver @ 15:42:28.920
_app-5ee16669ef044518.js:321 Mutations observed: 23
_app-5ee16669ef044518.js:321 ignoreSelector: .leaflet-proxy.leaflet-zoom-animated
_app-5ee16669ef044518.js:321 Applying data-iframe-ignore to: <div class=​"leaflet-proxy leaflet-zoom-animated" style=​"transform:​ translate3d(2.0898e+06px, 1.44012e+06px, 0px)​ scale(8192)​;​" data-iframe-ignore data-iframe-overflowed>​</div>​
_app-5ee16669ef044518.js:321 Tagged elements found: false
_app-5ee16669ef044518.js:321 Attached overflowObservers
_app-5ee16669ef044518.js:321 Attached resizeObserver: DIV.oa-1klo54e leaflet-container leaflet-touch leaflet-fade-anim leaflet-touch-zoom leaflet-gesture-handling
_app-5ee16669ef044518.js:321 Attached resizeObserver: DIV.leaflet-pane leaflet-map-pane
_app-5ee16669ef044518.js:321 Attached resizeObserver: DIV.leaflet-pane leaflet-tile-pane
_app-5ee16669ef044518.js:321 Attached resizeObserver: DIV.leaflet-layer 
_app-5ee16669ef044518.js:321 Attached resizeObserver: DIV.leaflet-tile-container leaflet-zoom-animated
2_app-5ee16669ef044518.js:321 Attached resizeObserver: IMG.leaflet-tile
_app-5ee16669ef044518.js:321 Attached resizeObserver: DIV.leaflet-pane leaflet-overlay-pane
_app-5ee16669ef044518.js:321 Attached resizeObserver: DIV.leaflet-pane leaflet-shadow-pane
_app-5ee16669ef044518.js:321 Attached resizeObserver: DIV.leaflet-pane leaflet-marker-pane
_app-5ee16669ef044518.js:321 Attached resizeObserver: IMG.leaflet-marker-icon leaflet-zoom-animated leaflet-interactive
_app-5ee16669ef044518.js:321 Attached resizeObserver: DIV.leaflet-pane leaflet-tooltip-pane
_app-5ee16669ef044518.js:321 Attached resizeObserver: DIV.leaflet-pane leaflet-popup-pane
_app-5ee16669ef044518.js:321 Attached resizeObserver: DIV.leaflet-top leaflet-left
_app-5ee16669ef044518.js:321 Attached resizeObserver: DIV.leaflet-control-zoom leaflet-bar leaflet-control
_app-5ee16669ef044518.js:321 Attached resizeObserver: DIV.leaflet-top leaflet-right
_app-5ee16669ef044518.js:321 Attached resizeObserver: DIV.leaflet-bottom leaflet-left
_app-5ee16669ef044518.js:321 Attached resizeObserver: DIV.leaflet-bottom leaflet-right
_app-5ee16669ef044518.js:321 Attached resizeObserver: DIV.leaflet-control-attribution leaflet-control
widgets.js:1 parent(oa-embed-0) overflowObserver @ 15:42:28.922
widgets.js:1 Received: [iFrameSizer]oa-embed-0:1486.3125:1140:overflowObserver
widgets.js:1 Set height: 1486.3125px
4560.699ac1f5cd896295.js:14 oa-embed-0 overflowObserver @ 15:42:28.923
_app-5ee16669ef044518.js:321 Observed Elements: 3
_app-5ee16669ef044518.js:321 Resize event: Overflow updated
_app-5ee16669ef044518.js:321 Found element overflowing <html> 
_app-5ee16669ef044518.js:321 Bottom position calculated from: <div class=​"leaflet-proxy leaflet-zoom-animated" style=​"transform:​ translate3d(2.0898e+06px, 1.44012e+06px, 0px)​ scale(8192)​;​" data-iframe-ignore data-iframe-overflowed>​</div>​
_app-5ee16669ef044518.js:321 Content height: 1440569.125px
_app-5ee16669ef044518.js:321 Size calculated in 0.3ms
_app-5ee16669ef044518.js:321 Sending message to host page via postMessage
_app-5ee16669ef044518.js:321 oa-embed-0:1440569.125:1140:overflowObserver
widgets.js:1 parent(oa-embed-0) overflowObserver @ 15:42:28.925
widgets.js:1 Received: [iFrameSizer]oa-embed-0:1440569.125:1140:overflowObserver
widgets.js:1 Set height: 1440569.125px
```

Same but colored:

![Image](https://github.com/user-attachments/assets/b9ef968c-9d5b-477d-831c-131ea7da04f3)

![Image](https://github.com/user-attachments/assets/da5bb6e0-5673-4c7a-9bfa-841df7728634)

**Comment by davidjbradshaw** [comment]
Thank you that is useful. I think we need to add a check to `packages/child/overflow.js`, so that it ignores nodes with `data-iframe-ignore`.  If you want to give it a try. Right now I need to sleep some more.

**Comment by davidjbradshaw** [comment]
Released `v5.4.0`

**Comment by davidjbradshaw** [comment]
Thanks for all your help. I was wondering if you could do me a favour and give my new [auto-console-group](/davidjbradshaw/auto-console-group) project that is making the new pretty log output a star.

**Comment by bertho-zero** [comment]
Done 👍
