### ISSUE TITLE
Not resizing in chrome on ios

### ISSUE THREAD

**Issue by DaleCollins** [davidjbradshaw/iframe-resizer#184]
Hi, I have implemented the script on a site i'm working on and it is working great on everything except Chrome on iOS. Is this a known issue or would you have a suggestion on how i could resolve the issue?
Standard install.

**Comment by davidjbradshaw** [comment]
Just tested the example and with the exception of the 'max' resize method it seems to work. Can you give me more details.

**Comment by davidjbradshaw** [comment]
Should be fixed in v2.8.6.

**Comment by DaleCollins** [comment]
Hi David,

I have downloaded 2.8.6, the problem still persists.
This is my setup:
<script type="text/javascript">
$(document).ready(function(){
	$('iframe').iFrameResize({heightCalculationMethod: 'lowestElement', interval: 500});
});
</script>

Works fine on everything except Chrome on iOS. Quite an unusual issue.
Any assistance would be greatly appreciated.

**Comment by davidjbradshaw** [comment]
Can you please give me a link to an example of this problem, I'm unable to reproduce it.

**Comment by ADAGUDELO** [comment]
good morning @davidjbradshaw , For the chrome browser version 42.0.2311.135 m, using iframeResizer.contentWindow.min.js, the website does not appear, to appear, the user must resize the window to display its contents. I used the verision 2.7.0, 2.7.1 and the latest release 2.8.6, and error persists. This problem has been presented in the last two weeks. I thank the attention and prompt response in case of need a test case or an example please sendme a message.

step 1
login in the website and navigate in chrome browsser
(the issue only happens u}in this page, in others pages it loads correctly)

step 2
we cannot see the content
![image](https://cloud.githubusercontent.com/assets/12303212/7524199/e25740da-f4c5-11e4-8156-7457cd73d1aa.png)

Paso 3
resizing the site to show content
![image](https://cloud.githubusercontent.com/assets/12303212/7524137/923ae2be-f4c5-11e4-9616-0c877d9e8448.png)

**Comment by davidjbradshaw** [comment]
Can you send me a link to take a look at this please.

**Comment by davidjbradshaw** [comment]
Or failing that post the complete log output here.

**Comment by ADAGUDELO** [comment]
Have a phone number where we can communicate, so we will explain the case occurred,

thanks

**Comment by marknoble** [comment]
Telephone? People still use those things?!? It's almost as if Skype weren't invented over a decade ago. 😆

**Comment by davidjbradshaw** [comment]
I would rather you just send me an example of the problem to look at. Can you make a simple test case?

**Comment by davidjbradshaw** [comment]
See #198 for a possible solution.

If that does not fix, then please post console log here.

**Comment by ADAGUDELO** [comment]
thank you very much for your support; and David solcione disadvantage.
Changing the iFrame html markup that contienela product to incorporate the recommended in the report of the google Chrome bug that does not show the contents of iFrames to resize the window workaround.

that error is reported since 2014 in Google Chrome
https://github.com/davidjbradshaw/iframe-resizer/issues?utf8=%E2%9C%93&q=is%3Aissue+chrome

Greetings.
