### ISSUE TITLE
auto resizer not working by default 4.0.1 but it does on 3.6.5

### ISSUE THREAD

**Issue by mgl97t** [davidjbradshaw/iframe-resizer#668]
I downloaded 4.0.1, opened /example/index.html and it is not auto resizing. I downloaded 3.6.5 and open /example/index.html and it auto resizes perfectly.

Is there a setting that I am missing?

Thanks!

**Comment by davidjbradshaw** [comment]
Bugger, Looks like I missed something when I released this. I'm seeing everything work except resizing the window. Is their any other broken use case?

**Comment by davidjbradshaw** [comment]
Fixed in v4.0.2, thanks for raising the issue.

**Comment by nelsondaza** [comment]
This error is back in 4.1.1
I did fix it changing
`iframe.src` for `iframe.getAttribute('src')`
in `iframeResizer.js`
